// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSveXJ7VuQg8XP0ob5NRB67DbZrMfHdBY',
    appId: '1:696204654604:web:3c910fd5551d26f79a5629',
    messagingSenderId: '696204654604',
    projectId: 'farm-management-system-edda7',
    authDomain: 'farm-management-system-edda7.firebaseapp.com',
    storageBucket: 'farm-management-system-edda7.firebasestorage.app',
    measurementId: 'G-13T1KV7845',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-FpblHUeJTMrPFF3NJY0IuB8J6adcTU',
    appId: '1:696204654604:android:4721a8434d60cb1b9a5629',
    messagingSenderId: '696204654604',
    projectId: 'farm-management-system-edda7',
    storageBucket: 'farm-management-system-edda7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ueYSH5FtsQVpetdwUz3vBl8IetQ7mQI',
    appId: '1:696204654604:ios:8b741ea5b3a5fd989a5629',
    messagingSenderId: '696204654604',
    projectId: 'farm-management-system-edda7',
    storageBucket: 'farm-management-system-edda7.firebasestorage.app',
    iosBundleId: 'com.example.farmManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ueYSH5FtsQVpetdwUz3vBl8IetQ7mQI',
    appId: '1:696204654604:ios:8b741ea5b3a5fd989a5629',
    messagingSenderId: '696204654604',
    projectId: 'farm-management-system-edda7',
    storageBucket: 'farm-management-system-edda7.firebasestorage.app',
    iosBundleId: 'com.example.farmManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSveXJ7VuQg8XP0ob5NRB67DbZrMfHdBY',
    appId: '1:696204654604:web:d5c03c67e10c3f5a9a5629',
    messagingSenderId: '696204654604',
    projectId: 'farm-management-system-edda7',
    authDomain: 'farm-management-system-edda7.firebaseapp.com',
    storageBucket: 'farm-management-system-edda7.firebasestorage.app',
    measurementId: 'G-MXWVHJZ0NB',
  );
}
